### ISSUE TITLE
关于预防个人信息扩散的一点建议 / Personal information leakage issue

### ISSUE THREAD

**Issue by Chigusa0w0** [iikira/baidu-tools#1]
```
post["_client_type"] = "2"
post["_client_version"] = "6.9.*.*"
post["_phone_imei"] = "8609********682"
post["from"] = "mini_ad_wandoujia"
post["model"] = "HUAWEI NXT-****"
post["cuid"] = "61464018************************************30389068"
```

使用如上所示的硬编码个人信息可能会导致这些信息被恶意利用。
建议采用多选项随机or完全随机方式生成信息。
您的项目`iikira/Baidu-Login`也存在此问题。

Using of hard-coded information as exampled above without randomize could lead to a leakage of your personal info.
Please implement mechanism to let the tool generate them per se instead of just code them into source files.
The same issue also appeared in your project `iikira/Baidu-Login`.

**Comment by iikira** [comment]
只有imei值得隐藏吧，cuid是根据上面的值算出来的，不懂怎么算。也不知百度会不会验证此值，索性就全贴出来咯……

**Comment by Chigusa0w0** [comment]
在baidu-login里你还把自己的百度uid和相关的个人主页url也给写进代码了……
可以试试看是不是必要字段，如果不是的话完全可以舍去。要是必需字段+会被校验，多找几台设备的数据每次随机也是好的。

**Comment by iikira** [comment]
真没注意这个，还有那个uid貌似只是时间戳😊
